import { State } from "./types";
/*
 * define state here
 */
export default (): State => ({
  trip: {
    id: "",
    outbound_from: "",
    outbound_to: "",
    outbound_from_datetime: "",
    outbound_to_datetime: "",
    outbound_timezone: "",
    return_from: "",
    return_to: "",
    return_from_datetime: "",
    return_to_datetime: "",
    return_timezone: "",
    route_points: "",
    trip_type: "",
    passenger_goal: 0,
    booking_reference: "",
    embedded_link: "",
    trip_status: "",
    is_published: false,
    regular_ticket_price: 0,
    earlybird_ticket_price: 0,
    total_regular_tickets: 0,
    available_regular_tickets: 0,
    total_earlybird_tickets: 0,
    available_earlybird_tickets: 0,
    total_cancelled_tickets: 0,
    deadline_ticket_selling: "",
    name: "",
    category: "",
    trip_organizer: "",
    info_to_travellers: "",
    website_url: "",
    image_url: "",
    max_pax: 0,
    discount_scheme: "",
    vat_percent: 0,
    deadline_passenger_goal: "",
    updated_at: "",
    country: "",
    minimum_possible_ticket_price: 0,
  },
  currentStep: 1,
  availablePublicTrips: {
    nextToken: "",
    items: [],
    total: 0,
  },
});
