phrase:
  access_token: 35d4373548e0bcf6b57a7f16dacf865f6d056a1828291fd89efeb14237c1cc84
  project_id: 8c6badc0a3bf0fb0ec8bebc20be8f007
  push:
    sources:
      - file: ./src/locales/<locale_name>.json
        params:
          file_format: i18next
          update_translations: true

  pull:
    targets:
      - file: ./src/locales/<locale_name>.json
        params:
          file_format: i18next
