export const enum TRIP_STATUS {
  NEW = "NEW",
  UNCONFIRMED = "UNCONFIRMED",
  CONFIRMED = "CONFIRMED",
  CANCELED_BY_ORGANIZER = "CANCELED_BY_ORGANIZER",
  CANCELED_BY_FERDIA = "CANCELED_BY_FERDIA",
  EXPIRED = "EXPIRED",
  WAITING_TO_START = "WAITING_TO_START",
  ONGOING = "ONGOING",
  FINISHED = "FINISHED",
  TERMINATED = "TERMINATED",
  CANCELED_BY_SALES = "CANCELED_BY_SALES",
}
export const enum TRIP_TYPE {
  ROUND = "ROUND",
  SINGLE = "SINGLE",
}
export const enum SHARE_LEAD_PAYMENT_STATUS {
  REQUIRED = "REQUIRED",
  PAID = "PAID",
  NOT_NEEDED = "NOT_NEEDED",
}

export const enum TRIP_FILTER {
  ACTIVE,
  UNPUBLISHED,
  ARCHIVED,
  CANCELLED,
}
