export enum ROUTE {
  HOME = "home",
  SETUP_SHAREBUS = "setup-sharebus",
  PUBLISH_SHAREBUS = "publish-sharebus",
  SHARELEAD_BUSSES = "share-lead-buses",
  SHARELEAD_TRIP_PAGE = "trip-page",
  JOINER_TRIPS = "joiner-trips",
  JOINER_BOOK_TICKET = "book-ticket",
  JOINER_TRIP_PAGE = "Joiner-trip-page",
  SALES_TRIP_PAGE = "trip-sales-page",
  SALES_TRIPS = "sales-buses",
  PARTNER_SHARELEAD_TRIP_PAGE = "trip-sales-page",
  PARTNER_SHARELEAD_TRIPS = "sales-buses",
  JOINER_CANCEL_BOOKING = "cancel-booking",
  TRIP_MAP = "trip-map",
  SHAREBUS_CREATE_CONFIRMATION = "sharbus-confirmation",
  PAYMENT = "payment",
}
