import { State } from "./types";
/*
 * define state here
 */
export default (): State => ({
  currentTrip: {
    id: "",
    booking_reference: "",
    monetary_value: {
      amount: 0,
      currency: "",
    },
    requester: "",
    outbound_from: "",
    outbound_from_lat_long: {
      lat: 0,
      lng: 0,
    },
    outbound_to: "",
    outbound_to_lat_long: {
      lat: 0,
      lng: 0,
    },
    outbound_from_datetime: "",
    outbound_to_datetime: "",
    outbound_timezone: "",
    return_from: "",
    return_from_lat_long: {
      lat: 0,
      lng: 0,
    },
    return_to: "",
    return_to_lat_long: {
      lat: 0,
      lng: 0,
    },
    return_from_datetime: "",
    return_to_datetime: "",
    return_timezone: "",
    route_points: "",
    country: "",
    trip_type: "",
    bus_availability: false,
    max_pax: 0,
    max_pax_teq: 0,
    passenger_goal: 0,
    minimum_pax: 0,
    sales_channel: "",
    organization: {
      id: 0,
      name: "",
      organization_number: "",
      parent_id: "",
    },
    trip_status: "",
    subsidy: {
      total_amount: {
        amount: 0,
        currency: "",
      },
      balance_amount: {
        amount: 0,
        currency: "",
      },
    },
    total_earlybird_tickets: 0,
    total_regular_tickets: 0,
    deadline_ticket_selling: "",
    available_earlybird_tickets: 0,
    available_regular_tickets: 0,
    regular_ticket_price: 0,
    earlybird_ticket_price: 0,
    name: "",
    category: "",
    info_to_travellers: "",
    website_url: "",
    image_url: "",
    digital_sign: "",
    discount_scheme: "",
    year: 0,
    club_share_per_extra_ticket: 0,
    is_published: false,
    trip_organizer: "",
    sharelead_ticket_reserved_price: 0,
    sharelead_contributed_amount: 0,
    tickets_reserved: 0,
    embedded_link: "",
    ticket: [],
    vat_percent: 0,
    deadline_passenger_goal: "",
    deadline_passenger_goal_reminder: "",
    deadline_trip_reminder: "",
    updated_at: "",
    update_history: {
      trip_location_time: "",
      trip_goal: "",
      trip_general_info: "",
      trip_deadline_passenger_goal: "",
      trip_ticket_discounts: "",
      trip_republish: "",
      updated_by_ferdia_sales: "",
      updated_by_sharelead: "",
      // new fields for new sharelead sales flow
      trip_ticket_pricing: "",
      trip_pax: "",
      show_trip_available_seats: "",
    },
    ticket_pricing: {
      categories: [
        { name: "Adult", enabled: true },
        { name: "Child", enabled: true },
        { name: "Senior", enabled: false },
      ],
      via_points: [],
    },
    show_available_seats: false,
    ticket_discounts: [],
    minimum_possible_ticket_price: 0,
  },
  tripList: {
    nextToken: "",
    total: 0,
    items: [],
  },
});
