phrase:
  access_token: 6f9a20af6dcae652f8a90f014bd80ebde3a57a773709d78cc78d66c8afa83c91
  project_id: 8c6badc0a3bf0fb0ec8bebc20be8f007
  push:
    sources:
    - file: ./src/locales/<locale_name>.json
      params:
        file_format: i18next
  pull:
    targets:
    - file: ./src/locales/<locale_name>.json
      params:
        file_format: i18next
